Pidev/src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:"La date de la réclamation est obligatoire")]
   
    #[Assert\Date(message:"La date de la réclamation doit etre de type date")]
    ///**
     //* @Assert\GreaterThanOrEqual("today", message="La date ne peut pas être postérieure à la date actuelle.")
     //*/
    private ?String $date_Reclamtion = null;

    #[ORM\Column(type: Types::TEXT)]    
    #[Assert\NotBlank(message:"La description de la réclamation est obligatoire")]
    #[Assert\Length(min:10,minMessage:"La description de la réclamation doit comporter au moins {{ limit }} caractéres")]
    private ?string $descriptionReclamation= null;


   
    

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message:"Le type de la réclamation est obligatoire")]
    private ?String $type_reclamation = null;

    #[ORM\OneToOne(inversedBy: 'idreclamation', cascade: ['persist', 'remove'])]
    private ?Reponse $idreponse = null;
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReclamtion(): ?String
    {
        return $this->date_Reclamtion;
    }

    public function setDateReclamtion(String $date_Reclamtion): self
    {
        $this->date_Reclamtion = $date_Reclamtion;

        return $this;
    }

    public function getDescriptionReclamation(): ?string
    {
        return $this->descriptionReclamation;
    }

    public function setDescriptionReclamation(string $descriptionReclamation): self
    {
        $this->descriptionReclamation = $descriptionReclamation;

        return $this;
    }

  

    public function getTypeReclamation(): ?string
    {
        return $this->type_reclamation;
    }

    public function setTypeReclamation(string $type_reclamation): self
    {
        $this->type_reclamation = $type_reclamation;

        return $this;
    }
    public function _toString(){
        return (string) $this->type_reclamation;
    }

    public function getIdreponse(): ?Reponse
    {
        return $this->idreponse;
    }

    public function setIdreponse(?Reponse $idreponse): self
    {
        $this->idreponse = $idreponse;

        return $this;
    }
   
   
}

Pidev/src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Entity\Reponse;


class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('dateReclamtion')
            ->add('descriptionReclamation')
            ->add('type_reclamation', ChoiceType::class, [
                'choices' => [
                    'Commande' => 'Commande',
                    'Activité' =>'Activité',
                    'Magasin'=>'Magasin',
                    'Abonnement'=>'Abonnement',


                ]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
    

   
}

Pidev/src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ReclamationRepository;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Reclamation;
use App\Form\ReclamationType;
use Doctrine\Persistence\ManagerRegistry;
use Mpdf\Mpdf;
use Dompdf\Options;
use Dompdf\Dompdf;
use TCPDF;


class ReclamationController extends AbstractController
{
    #[Route('/reclamation', name: 'app_reclamation')]
    public function index(): Response
    {
        return $this->render('reclamation/index.html.twig', [
            'controller_name' => 'ReclamationController',
        ]);
    }
     /**
    * @Route("/listreclamation/", name="reclamation")
    */
   public function listReclamation(ReclamationRepository $repository)
   {
       $reclamations=$this->getDoctrine()->getRepository(Reclamation::class)->findAll();
       //$reclamations =$repository->findAll();
       
       return $this->render('reclamation/list.html.twig', array("reclamations" => $reclamations));
    }   
   
    /**
     * @Route("/addReclamation", name="addReclamation")
     */
    public function addReclamation(Request $request)
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);
        $myDictionary = array(
            "tue", "merde",
            "gueule",
            "débile",
            "con",
            "abruti",
            "clochard",
            "sang"
        );
        dump($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $myText = $request->get("reclamation")['descriptionReclamation'];
            $badwords = new PhpBadWordsController();
            $badwords->setDictionaryFromArray($myDictionary)
                ->setText($myText);
            $check = $badwords->check();
            dump($check);
            if ($check) {
                $this->addFlash(
                    'info',
                    'Mot inapproprié!',
                );
            } else {
            $em = $this->getDoctrine()->getManager();
            $em->persist($reclamation);
            $em->flush();
            $this->addFlash(
                'info',
                'Reclamation ajoutée avec succés!'
            );
        }
            return $this->redirectToRoute('addReclamation');
        }
        return $this->render("reclamation/index.html.twig",array('form'=>$form->createView()));
} 
    
    // /**
    //  * @Route("/deleteR/{id}", name="deleteReclamation")
    //  */
    // public function deleteReclamation(ManagerRegistry $doctrine, $id):Response
    // {
        
    //     $em = $this->getDoctrine()->getManager();
    //     $em->remove($reclamations);
    //     $em->flush();
    //     return $this->redirectToRoute('reclamations');
    // }
    #[Route('/deleteR/{id}',name:'deleteReclamation')]
public function delete (ManagerRegistry $doctrine, $id):Response
{   $repository=$doctrine->getRepository(Reclamation::class);
    $reclamation=$repository->find($id);
    $em= $doctrine->getManager();
    $em->remove($reclamation);
    $em->flush();
    $this->addFlash(
        'del',
        'Reclamation supprimée avec succés!'
    );
    return $this->redirectToRoute('reclamation');
}
// /* /**
//      * @Route("/stats", name="stats")
//      */
//     public function statistiques(ReclamationRepository $reclamation){
//         // On va chercher toutes les types
//         $menus = $reclamation->findAll();

// //Data Category
//         $Commande = $reclamation->createQueryBuilder('a')
//             ->select('count(a.id)')
//             ->Where('a.type_reclamation= :type_reclamation')
//             ->setParameter('type_reclamation',"Commande")
//             ->getQuery()
//             ->getSingleScalarResult();
// $Magasin= $reclamation->createQueryBuilder('a')
//             ->select('count(a.id)')
//             ->Where('a.type_reclamation= :type_reclamation')
//             ->setParameter('type_reclamation',"Magasin")
//             ->getQuery()
//             ->getSingleScalarResult();
//        /*  $Activité= $reclamation->createQueryBuilder('a')
//             ->select('count(a.id)')
//             ->Where('a.type_reclamation= :type_reclamation')
//             ->setParameter('type_reclamation',"Activité")
//             ->getQuery()
//             ->getSingleScalarResult();
//             $Abonnement= $reclamation->createQueryBuilder('a')
//             ->select('count(a.id)')
//             ->Where('a.type_reclamation= :type_reclamation')
//             ->setParameter('type_reclamation',"Abonnement")
//             ->getQuery()
//             ->getSingleScalarResult(); */
//      return $this->render('Stats/stats.html.twig', [
//            /*  'nact' => $Activité,
//             'nabon' => $Abonnement, */
//             'nmag' => $Magasin,
//             'ncom' => $Commande,


//         ]);
//     } */
    /**
     * @Route("/listrec", name="listrec", methods={"GET"})
     */
    public function list(ReclamationRepository $FootRepository): Response
    {
        // Configure Dompdf according to your needs
        $pdfoptions = new Options();
        $pdfoptions->set('defaultFont', 'Arial');
        $pdfoptions->set('tempDir', '.\www\DaryGym\public\uploads\images');
// Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfoptions);
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reclamation/list.html.twig', [
            'reclamations' => $FootRepository->findAll(),
        ]);
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
// (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (inline view)
        $dompdf->stream("mypdf.pdf", [
"Attachment" => false
        ]);
    }
    /**
     * @Route("/TrierspcASC", name="triespc",methods={"GET"})
     */

     public function trierSpecialite(Request $request, ReclamationRepository $ArbitreMatchRepository): Response
     {
 
         $ArbitreMatchRepository = $this->getDoctrine()->getRepository(Reclamation::class);
         $arb = $ArbitreMatchRepository->tri();
 
         return $this->render('reclamation/list.html.twig', [
             'reclamations' => $arb,
         ]);
        }


     /**
     * @Route("/search", name="recherchetype", methods={"GET"})
     */

    public function searchoffreajax(Request $request, ReclamationRepository $FootRepository): Response
    {
        $FootRepository = $this->getDoctrine()->getRepository(Reclamation::class);
        $requestString = $request->get('searchValue');
        $foot = $FootRepository->findmatchbytype($requestString);

        return $this->render('reclamation/list.html.twig', [
            "reclamations" => $foot
        ]);
    }

 /**
     * @Route("/stats", name="stats")
     */
    public function statistiques(ReclamationRepository $produitRepository){
       

        $entityManager = $this->getDoctrine()->getManager();
        $data = $entityManager->getRepository(Reclamation::class)->findAll();


        $marqData = array_map(function($datum) {
            return $datum->getId();
        }, $data);
       
        $prixData = array_map(function($datu) {
            return $datu->getDateReclamtion();
        }, $data);

        return $this->render('Stats/stats.html.twig', [
            'marqData' => json_encode($marqData),
            'prixData'=> json_encode($prixData)
        ]);

    }
  /**
     * @Route("/pdf", name="app_reclamation_list", methods={"GET"})
     */
    public function generatePdf(ReclamationRepository $reclamationRepository): Response
    {

        // Configure Dompdf according to your needs
        $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');
        
        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);
        $reclamations = $reclamationRepository->findAll();
   
       
        
        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('reclamation/pdf.html.twig', [
            'reclamations' => $reclamations,
        
        ]);
        
        // Load HTML to Dompdf
        $dompdf->loadHtml($html);
        
        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        // Output the generated PDF to Browser (force download)
        $dompdf->stream("mypdf.pdf", [
            "Attachment" => true
        ]);

    }



        
}

Pidev/templates/reclamation/index.html.twig
  {% extends 'base.html.twig' %}

{% block  body %}
<h1><center> Veuillez remplir le formulaire çi dessous afin de passer votre réclamation </center></h1>
{% for message in app.flashes('info') %}
        <div class="alert alert-success">
        {{message}}
    {% endfor %}
<br>
<br>
<br>


<div class="container">
<center>
<div>
{{form_start(form,{'attr': {'novalidate': 'novalidate'}})}}

 {{ form_row(form.dateReclamtion,{'attr': {'placeholder':'Date reclamation','class':'form-control-lg'}})}}<br>
{{ form_row(form.descriptionReclamation,{'attr': {'placeholder':'Description reclamation','class':'form-control-lg'}})}}<br>
{{ form_row(form.type_reclamation,{'attr': {'placeholder':'Type reclamation','class':'form-control-lg'}})}}

<br>
   
<button type="submit" class="btn btn-round btn-facebook">Ajouter</button>

{{form_end(form)}}
</div>
</center>
</div>

<a href="{{path('listee') }}"><button type="submit" class="btn btn-round btn-facebook">Consulter mes réponses</button></a>
 {# {%  for a in  reponses %}
   <td> {{ a.dateReponse | date('d-m-y')}} </td>
        <td> {{ a.descriptionreponse }} </td>
   <button type="submit" class="btn btn-primary"> <a href="{{ path('listreponse',{'id' : a.id})}}"> Consulter mes réponses </button>
    </tr>
     
       {% endfor %} #}

{% endblock %}

Pidev/templates/reclamation/list.html.twig
{% extends 'baseback.html.twig' %}
{% block content %}



<div class="example-wrapper">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Réclamation</h4>
            <p class="card-description"> Gestion de <code>réclamations</code>
            </p>
            <section class="s-crossfit">
                <div class="container">
                    <h2>Rechercher réclamation </h2>

                    <div class="sidebar-search">

                        <div class="input-group custom-search-form">

                            <input type="text" id="search" class="form-control" placeholder="Search here">
                        </div>
                        <!-- /input-group -->
                    </div>

                    <div class="row" id="search">

                    </div>
                    <br><br><br><br>
                </div>
            </section>
            <script src="{{ asset('assets/js/jquery.js') }}"></script>
            <script
                    src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js')}}">
            </script>
            <script>
                $( document ).ready(function() {
                    var currentRequest = null;
                    $("#search").keyup(function(e){
                        /* La variable value va prendre la valeur insérer dans le champ de texte
                        afin d’effectuer la recherche */
                        var value = $(this).val();
                        if(currentRequest != null) {
                            currentRequest.abort();
                        }
                        /* Ajax est lancé lors du remplissage du champ texte dont l’id est
                        « search » pour faire la recherche */
                        currentRequest = $.ajax({
                            url : "{{ path('recherchetype') }}",
                            type : 'GET',
                            data: {
                                'searchValue' : value
                            },
                            success : function(retour)
                            {
                                $('#all').html(retour);
                            },
                        });
                        return false;
                    });
                });
            </script>



<div class=container>

<center>
<h1> Liste des réclamations</h1>
<table class="table">
    <tr> 
    <thead>
        <th > Date reclamation</th>
        <th > Description reclamation</th>
        
        <th > Type reclamation</th>
    </tr>
    <thead>
    <tbody>
    {%  for a in  reclamations %}
        <tr>
          
            <td>   {{ a.dateReclamtion|date("Y-m-d")}} </td>

            <td>   {{ a.descriptionReclamation }} </td>
          
            <td>   {{ a.typeReclamation }} </td>
                <td> <a class="btn btn-sm btn-danger" href="{{ path('deleteReclamation',{'id' : a.id}) }}">Supprimer </a></td>
            
        <td> <a class="btn btn-sm btn-success" href="{{ path('repondre', {id:a.id}) }}">Répondre </a></td>
        </tr>
    {% endfor %}
    <a href="{{path('stats') }}"><i class="btn btn-warning" data-feather="arrow-down"></i>Statistiques</a>
 {# <a href="{{path('listrec') }}"><i class="btn btn-warning" data-feather="arrow-down"></i>Générer pdf</a>  #}
</table>





<a href="{{path('triespc') }}"><i class="btn btn-danger" data-feather="arrow-down"></i>Tri ascendant </a>
</center>
{% for message in app.flashes('info') %}
        <div class="alert alert-success">
        {{message}}
    {% endfor %}
{% for message in app.flashes('del') %}
        <div class="alert alert-danger">
        {{message}}
    {% endfor %}
{% endblock %}

Pidev/templates/reclamation/pdf.html.twig
<div class=container>
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<h1> Liste des réclamations</h1>
<table class="table">
    <tr> 
    <thead>
        <th scope="col"> Date reclamation</th>
        <th scope="col"> Description reclamation</th>
        
        <th scope="col"> Type reclamation</th>
    </tr>
    <thead>
    <tbody>
    
    {%  for a in  reclamations %}
        <tr>
          
            <td>   {{ a.dateReclamtion|date("Y-m-d")}} </td>

            <td>   {{ a.descriptionReclamation }} </td>
          
            <td>   {{ a.typeReclamation }} </td>
                <td> <a class="btn btn-sm btn-danger" href="{{ path('deleteReclamation',{'id' : a.id}) }}">Supprimer </a></td>
            
        <td> <a class="btn btn-sm btn-success" href="{{ path('repondre', {id:a.id}) }}">Répondre </a></td>
        </tr>
    {% endfor %}
 
</table>

</center>

</div>

Pidev/templates/reclamation/update.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<div>
{{form_start(form,{'attr': {'novalidate': 'novalidate'}})}}
{{ form_widget(form) }}
{{ form_errors(form) }}
<button type="submit" class="btn btn-primary">Modifier</button>
{{form_end(form)}}
</div>
</center>
{% endblock %}