Pidev/src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank(message:"La date de la réclamation est obligatoire")]
   
    #[Assert\Date(message:"La date de la réclamation doit etre de type date")]
    ///**
     //* @Assert\GreaterThanOrEqual("today", message="La date ne peut pas être postérieure à la date actuelle.")
     //*/
    private ?String $date_Reclamtion = null;

    #[ORM\Column(type: Types::TEXT)]    
    #[Assert\NotBlank(message:"La description de la réclamation est obligatoire")]
    #[Assert\Length(min:10,minMessage:"La description de la réclamation doit comporter au moins {{ limit }} caractéres")]
    private ?string $descriptionReclamation= null;


   
    

    #[ORM\Column(length: 50)]
    #[Assert\NotBlank(message:"Le type de la réclamation est obligatoire")]
    private ?String $type_reclamation = null;

    #[ORM\OneToOne(inversedBy: 'idreclamation', cascade: ['persist', 'remove'])]
    private ?Reponse $idreponse = null;
   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReclamtion(): ?String
    {
        return $this->date_Reclamtion;
    }

    public function setDateReclamtion(String $date_Reclamtion): self
    {
        $this->date_Reclamtion = $date_Reclamtion;

        return $this;
    }

    public function getDescriptionReclamation(): ?string
    {
        return $this->descriptionReclamation;
    }

    public function setDescriptionReclamation(string $descriptionReclamation): self
    {
        $this->descriptionReclamation = $descriptionReclamation;

        return $this;
    }

  

    public function getTypeReclamation(): ?string
    {
        return $this->type_reclamation;
    }

    public function setTypeReclamation(string $type_reclamation): self
    {
        $this->type_reclamation = $type_reclamation;

        return $this;
    }
    public function _toString(){
        return (string) $this->type_reclamation;
    }

    public function getIdreponse(): ?Reponse
    {
        return $this->idreponse;
    }

    public function setIdreponse(?Reponse $idreponse): self
    {
        $this->idreponse = $idreponse;

        return $this;
    }
   
   
}

Pidev/templates/traitement_reclamation/index.html.twig
<br>
<br>
<br>
<br>
<br>
<center>
<div>
{{form_start(form,{'attr': {'novalidate': 'novalidate'}})}}

{{ form_widget(form)}}

{{ form_errors(form) }}
<button type="submit" class="btn btn-primary">Ajouter</button>
{{form_end(form)}}
</div>
</center>
{% endblock %}

Pidev/templates/traitement_reclamation/list.html.twig
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<h1> Liste des traitements des réclamations</h1>
<table border="1">
    <tr> 
        <th> dateReclamation</th>
        <th> descriptionReclamation</th>
        <th> Etat</th>
        <th> typeReclamation</th>
        <th> dateReponse </th>
        <th> descriptionreponse </th>
    </tr>
    {%  for a in  reclamations %}
        <tr>
            
            <td>   {{ a.dateReclamtion}} </td>
            <td>   {{ a.descriptionReclamation }} </td>
            <td>   {{ a.etat }} </td>
            <td>   {{ a.typeReclamation }} </td>

            <td> <a href="{{ path('updateReclamation', {id:a.id}) }}">Modifier </a></td>
            <td> <a href="{{ path('deleteReclamation', {id:a.id}) }}">Supprimer </a></td>
     {%  for a in  reponses %}
        <tr>
         <td>   {{ a.dateReponse}} </td>
         <td>   {{ a.descriptionreponse }} </td>
        </tr>
    {% endfor %}
</table>

</center>

Pidev/templates/traitement_reclamation/update.html.twig
<br>
<br>
<br>
<br>
<br>
<br>
<center>
<div>
{{form_start(form,{'attr': {'novalidate': 'novalidate'}})}}
{{ form_widget(form) }}
{{ form_errors(form) }}
<button type="submit" class="btn btn-primary">Modifier</button>
{{form_end(form)}}
</div>
</center>